### PR TITLE
canonical URLs on Page basis

### PR DESCRIPTION
**Pull request by lerni**
https://github.com/DorsetDigital/silverstripe-canonical/issues/1

### CODE REVIEW

**Comment by DorsetDigital** [comment]
Thanks Lukas.   I'll get this reviewed and merged ASAP.

**Comment by lerni** [comment]
cool - no stress ;) thx tim!

**Review by DorsetDigital — APPROVED** [review]

**Comment by DorsetDigital** [comment]
Thanks Lukas,

I'm going to do some local testing on the latest Silverstripe release and I'll tag a new module release.

**Comment by DorsetDigital** [comment]
Hi Lukas,

Any chance you could look at the logic around the canonical base here: https://github.com/DorsetDigital/silverstripe-canonical/blob/7dac5b78b7b11ed06f773f434f616f2d941ad270/src/SiteTreeCanonicalExtension.php#L49

In the condition, the code is checking to see if the scheme and host are not set (line 52), but then tries to access them if they aren't present (line 53) - throwing an error.  

Cheers
Tim

**Comment by DorsetDigital** [comment]
By the way, I'm back on Slack again now, so feel free to reach out to me there if you prefer to have a chat

**Pull request merged**
